name: CMake

on: [pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      shell: bash
      run: |
           sudo apt-get update
           sudo apt-get install octave octave-common octave-signal gnuplot sox p7zip-full

    - name: Create Build Directory
      shell: bash
      run: mkdir $GITHUB_WORKSPACE/build_linux

    - name: Configure codec2 CMake
      shell: bash
      working-directory: ${{github.workspace}}/build_linux
      run: cmake $GITHUB_WORKSPACE

    - name: Build codec2
      working-directory: ${{github.workspace}}/build_linux
      shell: bash
      run: make -j4

    - name: Build LPCNet
      shell: bash
      run: |
           cd $HOME
           git clone https://github.com/drowe67/LPCNet.git 
           cd LPCNet && mkdir -p build_linux && cd build_linux 
           cmake -DCODEC2_BUILD_DIR=$GITHUB_WORKSPACE/build_linux ..
           make
           # simple test to make sure the code runs
           cd src && sox ../../wav/wia.wav -t raw -r 16000 - | ./lpcnet_enc -s | ./lpcnet_dec -s > /dev/null

